import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, Bell, Bot, CalendarClock, Check, ChevronDown, CircleDollarSign, Clock3, Filter, Flame, Inbox, LayoutDashboard, Menu, MessageSquare, Plus, Search, Send, Settings, Sparkles, Target, TrendingUp, Users, X, Zap } from 'lucide-react';
import './styles.css';

const seedLeads = [
  { id:'L-1042',name:'Amara Okafor',company:'Northstar Properties',email:'amara@northstar.ng',value:4800,status:'Hot',stage:'Proposal',source:'Website',lastContact:'Today',nextFollowUp:'Today, 4:30 PM',message:'We need a property website with listings, WhatsApp enquiries and an admin panel.',score:94 },
  { id:'L-1041',name:'Daniel Mensah',company:'Kora Logistics',email:'daniel@koralogistics.com',value:3200,status:'Hot',stage:'Qualified',source:'Referral',lastContact:'Today',nextFollowUp:'Tomorrow, 9:00 AM',message:'Can you help us automate our quote requests and follow up with prospects?',score:88 },
  { id:'L-1040',name:'Sofia Bello',company:'Bello & Co.',email:'hello@belloco.com',value:1800,status:'Warm',stage:'New',source:'Landing page',lastContact:'Yesterday',nextFollowUp:'Tomorrow, 2:00 PM',message:'Interested in your service. What is the starting price?',score:73 },
  { id:'L-1039',name:'Tunde Adebayo',company:'Vertex Studio',email:'tunde@vertex.studio',value:2500,status:'Warm',stage:'Contacted',source:'Website',lastContact:'Yesterday',nextFollowUp:'Sep 14, 11:00 AM',message:'I saw your demo and would like to understand how the follow-up automation works.',score:67 },
  { id:'L-1038',name:'Maya Reed',company:'Maya Consulting',email:'maya@mayaconsulting.co',value:1200,status:'Cold',stage:'New',source:'Import',lastContact:'Sep 10',nextFollowUp:'Sep 16, 10:00 AM',message:'Please send more information about your plans.',score:42 }
];
const initialActivity=[
  {icon:'spark',text:'AI qualified Amara Okafor as a high-intent lead',time:'4 min ago'},
  {icon:'send',text:'Follow-up drafted for Daniel Mensah',time:'18 min ago'},
  {icon:'check',text:'Sofia Bello moved to qualified',time:'1 hr ago'},
  {icon:'zap',text:'Automation sequence completed for 3 leads',time:'2 hrs ago'}
];
const stages=['New','Contacted','Qualified','Proposal','Won'];
const storageKey='valo-mvp-leads-v1';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const cx=(...x)=>x.filter(Boolean).join(' ');

async function askValoAI(task,lead,instruction=''){
  const res=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,lead,instruction})});
  const data=await res.json();
  if(!res.ok) throw new Error(data.error||'AI request failed');
  return data.text;
}

function App(){
  const [leads,setLeads]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey))||seedLeads}catch{return seedLeads}});
  const [active,setActive]=useState('Overview'),[selectedId,setSelectedId]=useState('L-1042'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[showAdd,setShowAdd]=useState(false),[showMobileNav,setShowMobileNav]=useState(false),[activity,setActivity]=useState(initialActivity),[toast,setToast]=useState('');
  useEffect(()=>localStorage.setItem(storageKey,JSON.stringify(leads)),[leads]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(t)}},[toast]);
  const filteredLeads=useMemo(()=>leads.filter(l=>{const q=query.toLowerCase();return(!q||[l.name,l.company,l.email,l.message].some(v=>String(v).toLowerCase().includes(q)))&&(filter==='All'||l.status===filter||l.stage===filter)}),[leads,query,filter]);
  const selected=leads.find(l=>l.id===selectedId)||filteredLeads[0]||leads[0];
  const pipelineValue=leads.reduce((s,l)=>s+l.value,0),hotCount=leads.filter(l=>l.status==='Hot').length,followUps=leads.filter(l=>l.nextFollowUp.includes('Today')||l.nextFollowUp.includes('Tomorrow')).length;
  function addLead(data){const score=Number(data.score||60),lead={...data,id:`L-${1043+leads.length}`,score,status:score>=80?'Hot':score>=60?'Warm':'Cold',stage:'New',lastContact:'Just now',nextFollowUp:'Tomorrow, 10:00 AM'};setLeads(p=>[lead,...p]);setSelectedId(lead.id);setShowAdd(false);setActivity(p=>[{icon:'spark',text:`AI added ${lead.name} to the lead queue`,time:'Just now'},...p].slice(0,6));setToast('Lead added and scored by Valo.')}
  function updateStage(id,stage){setLeads(p=>p.map(l=>l.id===id?{...l,stage,status:stage==='Won'?'Won':l.status}:l));setActivity(p=>[{icon:'check',text:`Lead moved to ${stage}`,time:'Just now'},...p].slice(0,6));setToast(`Moved to ${stage}.`)}
  async function draftFollowUp(){setToast('Valo is drafting a reply…');try{const text=await askValoAI('draft_reply',selected,'Write a concise, natural sales follow-up that addresses the enquiry and moves the conversation toward a concrete next step. Do not invent pricing.');await navigator.clipboard?.writeText(text);setActivity(p=>[{icon:'send',text:`AI drafted a follow-up for ${selected.name}`,time:'Just now'},...p].slice(0,6));setToast('AI follow-up drafted and copied to clipboard.')}catch(e){setToast(e.message.includes('not configured')?'AI endpoint is ready — add OPENAI_API_KEY in deployment settings.':'AI draft failed. Check the server endpoint.')}}
  return <div className="app-shell">
    <aside className={cx('sidebar',showMobileNav&&'mobile-open')}><div className="brand"><div className="brand-mark">V</div><div><strong>valo</strong><span>AI SALES AUTOMATION</span></div></div><div className="workspace"><div className="workspace-avatar">A</div><div><b>Acme workspace</b><small>Growth team</small></div><ChevronDown size={15}/></div><nav><p className="nav-label">WORKSPACE</p>{[['Overview',LayoutDashboard],['Leads',Users],['Inbox',Inbox],['Follow-ups',CalendarClock],['Automations',Zap]].map(([label,Icon])=><button key={label} className={cx('nav-item',active===label&&'active')} onClick={()=>{setActive(label);setShowMobileNav(false)}}><Icon size={18}/><span>{label}</span>{label==='Inbox'&&<em>4</em>}</button>)}<p className="nav-label spaced">MANAGE</p>{['Customers','Analytics','Settings'].map(label=><button key={label} className={cx('nav-item',active===label&&'active')} onClick={()=>{setActive(label);setShowMobileNav(false)}}><span className="nav-dot"/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="usage"><div><span>AI usage</span><b>68%</b></div><div className="progress"><i style={{width:'68%'}}/></div><small>1,360 / 2,000 actions</small></div><button className="help"><MessageSquare size={16}/>Need help?</button></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setShowMobileNav(v=>!v)}><Menu/></button><div className="crumb">Workspace <span>/</span> {active}</div><div className="top-actions"><button className="icon-btn"><Search size={18}/></button><button className="icon-btn notify"><Bell size={18}/><i/></button><div className="user"><div className="user-avatar">YO</div><span>Owner</span><ChevronDown size={14}/></div></div></header>
      <section className="content"><div className="page-head"><div><p className="eyebrow">GOOD EVENING</p><h1>{active==='Overview'?'Your sales, on autopilot.':active}</h1><p className="sub">{active==='Overview'?'Valo is keeping your pipeline moving while you focus on closing.':'Manage your revenue workflow from one intelligent workspace.'}</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/>Add lead</button></div>
      {active==='Overview'?<><div className="metrics"><Metric icon={Target} label="Pipeline value" value={money(pipelineValue)} change="+18.4%" detail="vs last month"/><Metric icon={Flame} label="Hot leads" value={hotCount} change="+4" detail="this week"/><Metric icon={CalendarClock} label="Follow-ups" value={followUps} change="Due soon" detail="next 24 hours"/><Metric icon={TrendingUp} label="Win rate" value="31.8%" change="+6.2%" detail="vs last month"/></div><div className="grid-main"><section className="card pipeline-card"><div className="card-head"><div><h2>Sales pipeline</h2><p>Track every opportunity from enquiry to revenue.</p></div><button className="ghost" onClick={()=>setActive('Leads')}>View all <ArrowRight size={15}/></button></div><div className="pipeline">{stages.map(stage=>{const items=leads.filter(l=>l.stage===stage);return <div className="stage" key={stage}><div className="stage-head"><span>{stage}</span><b>{items.length}</b></div><div className="stage-line"/>{items.slice(0,3).map(l=><LeadCard key={l.id} lead={l} onClick={()=>{setSelectedId(l.id);setActive('Leads')}}/>)}{!items.length&&<div className="empty-stage">No leads</div>}</div>})}</div></section><section className="card ai-card"><div className="ai-orb"><Sparkles size={20}/></div><div className="ai-title"><div><span>VALO AI</span><h2>Sales copilot</h2></div><span className="live"><i/>Live</span></div><p className="ai-copy">Your AI has been working in the background. Here are the actions that need your attention.</p><div className="ai-task"><div className="task-icon hot"><Flame size={16}/></div><div><b>2 high-intent leads need replies</b><span>Amara and Daniel are waiting.</span></div><ArrowRight size={16}/></div><div className="ai-task"><div className="task-icon"><Clock3 size={16}/></div><div><b>3 follow-ups due today</b><span>Best time to contact: 4–6 PM.</span></div><ArrowRight size={16}/></div><button className="ai-button" onClick={()=>{setActive('Leads');setToast('Showing your highest-priority leads.')}}><Bot size={17}/>Ask Valo AI</button></section></div><div className="grid-bottom"><section className="card table-card"><div className="card-head"><div><h2>Priority leads</h2><p>Leads most likely to convert next.</p></div><button className="ghost" onClick={()=>setActive('Leads')}>Manage leads <ArrowRight size={15}/></button></div><LeadTable leads={leads.slice(0,5)} onSelect={id=>{setSelectedId(id);setActive('Leads')}}/></section><ActivityFeed activity={activity}/></div></>:<WorkspacePage active={active} leads={filteredLeads} onAdd={()=>setShowAdd(true)} onSelect={id=>setSelectedId(id)} onStage={updateStage} selected={selected} onDraft={draftFollowUp} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter}/>}</section></main>
    {active==='Leads'&&selected&&<LeadDrawer lead={selected} onClose={()=>setSelectedId(null)} onStage={updateStage} onDraft={draftFollowUp}/>} {showAdd&&<AddLeadModal onClose={()=>setShowAdd(false)} onAdd={addLead}/>} {toast&&<div className="toast"><Check size={17}/>{toast}</div>}
  </div>
}
function Metric({icon:Icon,label,value,change,detail}){return <div className="metric"><div className="metric-icon"><Icon size={18}/></div><div className="metric-body"><span>{label}</span><strong>{value}</strong><small><b>{change}</b> {detail}</small></div></div>}
function LeadCard({lead,onClick}){return <button className="lead-card" onClick={onClick}><div className="lead-top"><span className={cx('status',lead.status.toLowerCase())}>{lead.status}</span><span className="score">{lead.score}</span></div><b>{lead.name}</b><small>{lead.company}</small><div className="lead-bottom"><span>{money(lead.value)}</span><span>{lead.source}</span></div></button>}
function LeadTable({leads,onSelect}){return <div className="lead-table"><div className="table-row table-head"><span>Lead</span><span>Company</span><span>Value</span><span>Score</span><span>Next action</span></div>{leads.map(l=><button className="table-row" key={l.id} onClick={()=>onSelect(l.id)}><span className="person"><i>{l.name.split(' ').map(x=>x[0]).join('')}</i><b>{l.name}<small>{l.email}</small></b></span><span>{l.company}</span><span>{money(l.value)}</span><span><strong className={cx('score-pill',l.status.toLowerCase())}>{l.score}</strong></span><span>{l.nextFollowUp}</span></button>)}</div>}
function ActivityFeed({activity}){return <section className="card activity-card"><div className="card-head"><div><h2>Activity</h2><p>What Valo has done recently.</p></div><Activity size={17}/></div><div className="activity-list">{activity.map((a,i)=><div className="activity-item" key={i}><div className="activity-icon"><Sparkles size={14}/></div><div><b>{a.text}</b><span>{a.time}</span></div></div>)}</div></section>}
function WorkspacePage({active,leads,onAdd,onSelect,onStage,selected,onDraft,query,setQuery,filter,setFilter}){
  if(active==='Analytics')return <div className="analytics-grid"><section className="card chart-card"><div className="card-head"><div><h2>Revenue momentum</h2><p>Pipeline value over the last 30 days.</p></div><span className="chart-value">$14.8k <small>+18.4%</small></span></div><div className="fake-chart"><div className="chart-grid">{[1,2,3,4,5].map(i=><i key={i}/>)}</div><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path d="M0 190 C70 185 80 170 135 178 S205 120 260 145 S330 80 390 105 S470 125 520 65 S610 80 700 25" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M0 190 C70 185 80 170 135 178 S205 120 260 145 S330 80 390 105 S470 125 520 65 S610 80 700 25 V220 H0Z" fill="currentColor" opacity=".08"/></svg></div></section><Metric icon={CircleDollarSign} label="Won revenue" value="$8,420" change="+22.8%" detail="this month"/><Metric icon={Target} label="Qualified leads" value="27" change="+12" detail="this month"/><Metric icon={Zap} label="AI actions" value="186" change="+34%" detail="vs last month"/></div>;
  if(active==='Settings')return <SettingsPage/>;
  if(active==='Customers')return <div className="empty-page card"><Users size={30}/><h2>Customer workspace</h2><p>Customers are created automatically as leads progress through the pipeline. Your current MVP uses the same persistent local lead store.</p><button className="primary" onClick={onAdd}><Plus size={16}/>Add first customer</button></div>;
  if(active==='Inbox')return <div className="inbox-layout"><section className="card inbox-list"><div className="card-head"><div><h2>Conversation inbox</h2><p>Prioritized by intent.</p></div></div>{leads.slice(0,5).map(l=><button className="conversation" key={l.id} onClick={()=>onSelect(l.id)}><div className="avatar">{l.name.split(' ').map(x=>x[0]).join('')}</div><div><b>{l.name}</b><span>{l.message}</span></div><em>{l.status}</em></button>)}</section><section className="card inbox-detail"><MessageSquare size={28}/><h2>Select a conversation</h2><p>Choose a lead to inspect the conversation and let Valo draft the next reply.</p></section></div>;
  if(active==='Follow-ups'||active==='Automations')return <div className="card automation-page"><div className="card-head"><div><h2>{active}</h2><p>{active==='Follow-ups'?'Keep prospects moving without manual reminders.':'Rules that turn repetitive sales work into background jobs.'}</p></div><button className="primary"><Plus size={16}/>{active==='Follow-ups'?'Schedule follow-up':'Create automation'}</button></div><div className="automation-list">{['New lead → qualify within 2 minutes','No reply after 24h → send helpful follow-up','Qualified lead → alert owner','Proposal sent → follow up in 2 days'].map((x,i)=><div className="automation-row" key={x}><div className="task-icon"><Zap size={16}/></div><div><b>{x}</b><span>{i===0?'Active · AI qualification':'Active · monitored by Valo'}</span></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div>)}</div></div>;
  return <div className="leads-workspace"><section className="card leads-card"><div className="card-head"><div><h2>Lead command center</h2><p>Capture, qualify and move every opportunity.</p></div><button className="primary" onClick={onAdd}><Plus size={16}/>Add lead</button></div><div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leads..."/></div><button className="filter"><Filter size={15}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Hot</option><option>Warm</option><option>Cold</option><option>Qualified</option><option>Proposal</option></select></button></div><LeadTable leads={leads} onSelect={onSelect}/></section>{selected&&<section className="card quick-detail"><div className="detail-avatar">{selected.name.split(' ').map(x=>x[0]).join('')}</div><span className={cx('status',selected.status.toLowerCase())}>{selected.status} · {selected.score}/100</span><h2>{selected.name}</h2><p>{selected.company}</p><div className="detail-value">{money(selected.value)} <small>estimated value</small></div><div className="detail-message">“{selected.message}”</div><button className="ai-button" onClick={onDraft}><Sparkles size={16}/>Draft AI follow-up</button><label>Pipeline stage</label><div className="stage-select">{stages.map(s=><button className={selected.stage===s?'chosen':''} key={s} onClick={()=>onStage(selected.id,s)}>{s}</button>)}</div></section>}</div>;
}
function SettingsPage(){return <div className="settings-grid"><section className="card settings-card"><div className="settings-title"><div className="settings-icon"><Settings size={18}/></div><div><h2>Workspace settings</h2><p>Configure how Valo works for your team.</p></div></div>{[['Workspace name','Acme workspace'],['Default currency','USD — US Dollar'],['Lead scoring','AI assisted'],['Timezone','Africa/Lagos']].map(([a,b])=><label className="setting-row" key={a}><span>{a}</span><input defaultValue={b}/></label>)}<button className="primary">Save changes</button></section><section className="card settings-card"><div className="settings-title"><div className="settings-icon"><Bot size={18}/></div><div><h2>AI controls</h2><p>Keep consequential actions under human control.</p></div></div>{['Auto-score new leads','Draft replies automatically','Suggest follow-up timing','Send messages without review'].map((x,i)=><div className="toggle-row" key={x}><div><b>{x}</b><span>{i===3?'Off by default — enable only when you trust the workflow.':'Enabled for the workspace.'}</span></div><label className="switch"><input type="checkbox" defaultChecked={i!==3}/><span/></label></div>)}</section></div>}
function LeadDrawer({lead,onClose,onStage,onDraft}){return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span>Lead {lead.id}</span><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="drawer-profile"><div className="detail-avatar">{lead.name.split(' ').map(x=>x[0]).join('')}</div><div><h2>{lead.name}</h2><p>{lead.company}</p></div><span className={cx('status',lead.status.toLowerCase())}>{lead.status}</span></div><div className="drawer-score"><div><span>AI intent score</span><strong>{lead.score}<small>/100</small></strong></div><div className="score-ring"><span>{lead.score}</span></div></div><div className="drawer-section"><h3>Latest enquiry</h3><p>{lead.message}</p></div><div className="drawer-section"><h3>Next action</h3><div className="next-action"><Clock3 size={16}/><div><b>{lead.nextFollowUp}</b><span>Follow up with a helpful, specific answer.</span></div></div></div><div className="drawer-actions"><button className="secondary" onClick={onDraft}><Sparkles size={16}/>Draft reply</button><button className="primary" onClick={()=>onStage(lead.id,'Qualified')}><Check size={16}/>Qualify lead</button></div></aside></div>}
function AddLeadModal({onClose,onAdd}){const [form,setForm]=useState({name:'',company:'',email:'',value:'1500',message:'',score:'70'}),change=e=>setForm({...form,[e.target.name]:e.target.value});return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span>NEW OPPORTUNITY</span><h2>Add a lead</h2><p>Valo will score and prioritize it automatically.</p></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="form-grid"><label>Contact name<input name="name" value={form.name} onChange={change} placeholder="e.g. Amara Okafor" autoFocus/></label><label>Company<input name="company" value={form.company} onChange={change} placeholder="Company name"/></label><label>Email<input name="email" value={form.email} onChange={change} placeholder="name@company.com"/></label><label>Estimated value<input name="value" type="number" value={form.value} onChange={change}/></label><label className="full">Enquiry<textarea name="message" value={form.message} onChange={change} placeholder="Paste the customer's enquiry..."/></label><label>Intent score<input name="score" type="number" min="0" max="100" value={form.score} onChange={change}/></label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!form.name||!form.message} onClick={()=>onAdd({...form,value:Number(form.value)})}><Sparkles size={16}/>Add + score with AI</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
